name: .NET Build

on: [push, pull_request]

jobs:
  BuildInWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and Test
      run: |
        dotnet build --configuration release LightTextEditorPlus
        dotnet test --configuration release LightTextEditorPlus --no-build

  BuildInLinux:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v1

    - name: Build and Test
      run: |
        dotnet build --configuration release LightTextEditorPlus/LightTextEditorPlus.Core/LightTextEditorPlus.Core.csproj
        dotnet test --configuration release LightTextEditorPlus/Tests/LightTextEditorPlus.Core.Tests/LightTextEditorPlus.Core.Tests.csproj